// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd6fBf5BjHSl1MrZdsDqWCi7NM1pCuR8w',
    appId: '1:610788998259:web:f878f9b63463da7ce77e06',
    messagingSenderId: '610788998259',
    projectId: 'lsp-mobile-697a4',
    authDomain: 'lsp-mobile-697a4.firebaseapp.com',
    storageBucket: 'lsp-mobile-697a4.firebasestorage.app',
    measurementId: 'G-W96DHNDVV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs33-h7mxWR2B62w9hJuPZj8bOsmYjTDg',
    appId: '1:610788998259:android:6adab0efb022ead6e77e06',
    messagingSenderId: '610788998259',
    projectId: 'lsp-mobile-697a4',
    storageBucket: 'lsp-mobile-697a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo2PpKEKdH8x0y4TjUgCt-XZFxp_eN-No',
    appId: '1:610788998259:ios:676c4689a16158c5e77e06',
    messagingSenderId: '610788998259',
    projectId: 'lsp-mobile-697a4',
    storageBucket: 'lsp-mobile-697a4.firebasestorage.app',
    iosBundleId: 'com.example.lspDigitalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo2PpKEKdH8x0y4TjUgCt-XZFxp_eN-No',
    appId: '1:610788998259:ios:676c4689a16158c5e77e06',
    messagingSenderId: '610788998259',
    projectId: 'lsp-mobile-697a4',
    storageBucket: 'lsp-mobile-697a4.firebasestorage.app',
    iosBundleId: 'com.example.lspDigitalMobile',
  );
}
