// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR3yIbOH_ZDn7_E9sHDEYCf6lsYR3dxeQ',
    appId: '1:113874406807:web:f878f9b63463da7ce77e06',
    messagingSenderId: '113874406807',
    projectId: 'lsp-digital-mobile',
    authDomain: 'lsp-digital-mobile.firebaseapp.com',
    storageBucket: 'lsp-digital-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR3yIbOH_ZDn7_E9sHDEYCf6lsYR3dxeQ',
    appId: '1:113874406807:android:38e2fcc37d787fbf3ec8d2',
    messagingSenderId: '113874406807',
    projectId: 'lsp-digital-mobile',
    storageBucket: 'lsp-digital-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR3yIbOH_ZDn7_E9sHDEYCf6lsYR3dxeQ',
    appId: '1:113874406807:ios:676c4689a16158c5e77e06',
    messagingSenderId: '113874406807',
    projectId: 'lsp-digital-mobile',
    storageBucket: 'lsp-digital-mobile.firebasestorage.app',
    iosBundleId: 'com.example.lspDigitalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR3yIbOH_ZDn7_E9sHDEYCf6lsYR3dxeQ',
    appId: '1:113874406807:ios:676c4689a16158c5e77e06',
    messagingSenderId: '113874406807',
    projectId: 'lsp-digital-mobile',
    storageBucket: 'lsp-digital-mobile.firebasestorage.app',
    iosBundleId: 'com.example.lspDigitalMobile',
  );
}
